services:

  php:
    image: my_php_img
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./project:/project
    ports:
      - 9000:9000

  db:
    container_name: mysql
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    user: 1000:1000
    volumes:
      - mysql_data:/var/lib/mysql/
      - ./logs/mysql/:/var/log/mysql/
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./project:/project
    ports:
      - 80:80

networks:
  default:
    name: ${NETWORK_NAME}

volumes:
  mysql_data:
